Antonio Calzadilla Miranda

**Practica # 04 **
Manipulación de matrices

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

Suma ambas matrices.
Resta la segunda matriz de la primera.
Multiplica la primera matriz por 2.
Realiza una multiplicación matricial entre las dos matrices.
No olvides enviar tu .ipynb y el link de tu repositorio de github

In [2]:
import numpy as np
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
print("Matriz A:", A)
print("Matriz B:", B)
print("Suma de matrices:", A + B)
print("Resta de B - A:", B - A)
print("Multiplicación de A por 2:", np.dot(A, 2))
print("Multiplicación matricial:", np.dot(A, B))

Matriz A: [[5 5 3]
 [9 9 4]
 [9 9 3]]
Matriz B: [[2 9 8]
 [8 2 6]
 [6 7 7]]
Suma de matrices: [[ 7 14 11]
 [17 11 10]
 [15 16 10]]
Resta de B - A: [[-3  4  5]
 [-1 -7  2]
 [-3 -2  4]]
Multiplicación de A por 2: [[10 10  6]
 [18 18  8]
 [18 18  6]]
Multiplicación matricial: [[ 68  76  91]
 [114 127 154]
 [108 120 147]]
